services:
  postgres:
    image: postgres:16-alpine
    container_name: egisz-auth-db
    environment:
      POSTGRES_DB: egisz_auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
